spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          facebook:
            client-id: google-client-id
            client-secret: google-client-secret
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost:8011/mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

custom:
  oauth2:
    kakao:
      client-id: db0a86ebabc86d824d6227d4b3562af4

logging:
  level:
    com:
      community: debug
